Delete if condition

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,9 +24,5 @@ after_success:
   - java -jar sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar sourcecodeanalyzer/src/main/resources/TestClass.java regex local actual_metrics csv
   - echo "loc,noc,nom," > expected_metrics.csv
   - echo "21,3,3," >> expected_metrics.csv
-  - if [ !(cmp --silent actual_metrics.csv expected_metrics.csv) ]; then 
-    echo "WARNING: Integration test fail!";
-    exit 1;
-    fi
-  - echo "SUCCESS: Integration test pass!"
+  - (cmp --silent actual_metrics.csv expected_metrics.csv) && echo "SUCCESS: Integration test pass!" || (echo "WARNING: Integration test fail!" && exit 1)
 
