Add integration testing after success in .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -21,5 +21,12 @@ script:
 
 after_success:
   - bash <(curl -s https://codecov.io/bash) -t bffea5bd-7caa-4f7a-b0bf-bfcc4086577c
-
+  - java -jar sourcecodeanalyzer/target/sourcecodeanalyzer-0.0.1-SNAPSHOT-jar-with-dependencies.jar sourcecodeanalyzer/src/main/resources/TestClass.java regex local actual_metrics csv
+  - echo "loc,noc,nom," > expected_metrics.csv
+  - echo "21,3,3," >> expected_metrics.csv
+  - if [ !(cmp --silent actual_metrics.csv expected_metrics.csv) ]; then 
+    echo "WARNING: Integration test fail!";
+    exit 1;
+    fi
+  - echo "SUCCESS: Integration test pass!"
 
